name: CI
on:
  push:
  pull_request:
jobs:
  test:
    name: ${{ matrix.os }} tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt test-plugin
        shell: bash
